
-- find total customers by countries
SELECT 
country, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country ORDER BY total_customers DESC;

-- find total customers by gender
SELECT 
gender, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender;

-- find total products by category
SELECT
category, 
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- find average cost in each category
SELECT 
category,
AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- what is the total revenue generated for each category
SELECT SUM(f.sales_amount) AS total_revenue,
p.category FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP by p.category
ORDER BY total_revenue DESC;

-- total revenue generated by each customer
SELECT c.customer_key, c.first_name, c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC;

-- distribution of sold items across countries
SELECT c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;











